// -------------------------------------------------------------
// 
// File Name: C:\Users\Angel\Desktop\hil\ips\MCP_DRIVER\hdlsrc\int2bin_sdi\simfcn1.v
// Created: 2025-02-09 09:33:16
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: simfcn1
// Source Path: 
// Hierarchy Level: 2
// Model version: 3.52
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module simfcn1
          (vx,
           b_cont_bits_0,
           b_cont_bits_1,
           b_cont_bits_2,
           b_cont_bits_3,
           b_cont_bits_4,
           b_cont_bits_5,
           b_cont_bits_6,
           b_cont_bits_7);


  input   [7:0] vx;  // uint8
  output  [7:0] b_cont_bits_0;  // uint8
  output  [7:0] b_cont_bits_1;  // uint8
  output  [7:0] b_cont_bits_2;  // uint8
  output  [7:0] b_cont_bits_3;  // uint8
  output  [7:0] b_cont_bits_4;  // uint8
  output  [7:0] b_cont_bits_5;  // uint8
  output  [7:0] b_cont_bits_6;  // uint8
  output  [7:0] b_cont_bits_7;  // uint8


  wire tmp;
  wire [7:0] tmp_1;  // uint8
  wire tmp_2;
  wire [7:0] tmp_3;  // uint8
  wire tmp_4;
  wire [7:0] tmp_5;  // uint8
  wire tmp_6;
  wire [7:0] tmp_7;  // uint8
  wire tmp_8;
  wire [7:0] tmp_9;  // uint8
  wire tmp_10;
  wire [7:0] tmp_11;  // uint8
  wire tmp_12;
  wire [7:0] tmp_13;  // uint8
  wire tmp_14;
  wire [7:0] tmp_15;  // uint8
  wire [7:0] b_cont_bits [0:7];  // uint8 [8]


  // MATLAB Function 'simfcn1'
  assign tmp = vx[0] != 1'b0;
  assign tmp_1 = {7'b0, tmp};

  assign tmp_2 = vx[1] != 1'b0;

  assign tmp_3 = {7'b0, tmp_2};

  assign tmp_4 = vx[2] != 1'b0;

  assign tmp_5 = {7'b0, tmp_4};

  assign tmp_6 = vx[3] != 1'b0;

  assign tmp_7 = {7'b0, tmp_6};

  assign tmp_8 = vx[4] != 1'b0;

  assign tmp_9 = {7'b0, tmp_8};

  assign tmp_10 = vx[5] != 1'b0;

  assign tmp_11 = {7'b0, tmp_10};

  assign tmp_12 = vx[6] != 1'b0;

  assign tmp_13 = {7'b0, tmp_12};

  assign tmp_14 = vx[7] != 1'b0;

  assign tmp_15 = {7'b0, tmp_14};

  assign b_cont_bits[0] = tmp_15;
  assign b_cont_bits[1] = tmp_13;
  assign b_cont_bits[2] = tmp_11;
  assign b_cont_bits[3] = tmp_9;
  assign b_cont_bits[4] = tmp_7;
  assign b_cont_bits[5] = tmp_5;
  assign b_cont_bits[6] = tmp_3;
  assign b_cont_bits[7] = tmp_1;

  assign b_cont_bits_0 = b_cont_bits[0];

  assign b_cont_bits_1 = b_cont_bits[1];

  assign b_cont_bits_2 = b_cont_bits[2];

  assign b_cont_bits_3 = b_cont_bits[3];

  assign b_cont_bits_4 = b_cont_bits[4];

  assign b_cont_bits_5 = b_cont_bits[5];

  assign b_cont_bits_6 = b_cont_bits[6];

  assign b_cont_bits_7 = b_cont_bits[7];

endmodule  // simfcn1

