// -------------------------------------------------------------
// 
// File Name: C:\Users\Angel\Desktop\hil\ips\MCP_DRIVER\hdlsrc\int2bin_sdi\SPI_DAC_tc.v
// Created: 2025-02-09 07:59:34
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SPI_DAC_tc
// Source Path: SPI_DAC_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb         : identical to clk_enable
// enb_1_90000000_0: 90000000x slower than clk with last phase
// enb_1_90000000_1: 90000000x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SPI_DAC_tc
          (clk,
           rst,
           clk_enable,
           enb,
           enb_1_90000000_0,
           enb_1_90000000_1);


  input   clk;
  input   rst;
  input   clk_enable;
  output  enb;
  output  enb_1_90000000_0;
  output  enb_1_90000000_1;


  reg [26:0] count90000000;  // ufix27
  wire comp_0_tmp;
  wire phase_0_tmp;
  reg  phase_0;
  wire enb_1_90000000_0_1;
  wire comp_1_tmp;
  wire phase_1_tmp;
  reg  phase_1;
  wire enb_1_90000000_1_1;


  assign enb = clk_enable;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 89999999
  always @(posedge clk)
    begin : counter_90000000_process
      if (rst == 1'b1) begin
        count90000000 <= 27'b000000000000000000000000001;
      end
      else begin
        if (clk_enable) begin
          if (count90000000 >= 27'b101010111010100101001111111) begin
            count90000000 <= 27'b000000000000000000000000000;
          end
          else begin
            count90000000 <= count90000000 + 27'b000000000000000000000000001;
          end
        end
      end
    end

  assign comp_0_tmp = count90000000 == 27'b101010111010100101001111111;

  assign phase_0_tmp = comp_0_tmp & clk_enable;

  always @(posedge clk)
    begin : phase_delay_process
      if (rst == 1'b1) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end

  assign enb_1_90000000_0_1 = phase_0 & clk_enable;

  assign enb_1_90000000_0 = enb_1_90000000_0_1;

  assign comp_1_tmp = count90000000 == 27'b000000000000000000000000000;

  assign phase_1_tmp = comp_1_tmp & clk_enable;

  always @(posedge clk)
    begin : phase_delay_1_process
      if (rst == 1'b1) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clk_enable) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end

  assign enb_1_90000000_1_1 = phase_1 & clk_enable;

  assign enb_1_90000000_1 = enb_1_90000000_1_1;

endmodule  // SPI_DAC_tc

