// -------------------------------------------------------------
// 
// File Name: .\hdlsrc\int2bin_sdi\model_int2bin_sdi.v
// Created: 2024-11-01 08:51:56
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 8.33333e-09
// Target subsystem base rate: 1.66667e-07
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: model_int2bin_sdi
// Source Path: int2bin_sdi/model_int2bin_sdi
// Hierarchy Level: 0
// Model version: 3.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module model_int2bin_sdi
          (clk,
           rst,
           v1_1,
           v1_2,
           v2_1,
           v2_2,
           v3_1,
           v3_2,
           num_vx_x,
           SDI,
           SCK,
           nCS1,
           nCS2,
           nCS3);


  input   clk;
  input   rst;
  input   [7:0] v1_1;  // uint8
  input   [7:0] v1_2;  // uint8
  input   [7:0] v2_1;  // uint8
  input   [7:0] v2_2;  // uint8
  input   [7:0] v3_1;  // uint8
  input   [7:0] v3_2;  // uint8
  input   [7:0] num_vx_x;  // uint8
  output  SDI;
  output  SCK;
  output  nCS1;
  output  nCS2;
  output  nCS3;


  wire in2bin_out1;
  wire in2bin_out2;
  wire in2bin_out3;
  wire in2bin_out4;
  wire in2bin_out5;


  in2bin u_in2bin (.clk(clk),
                   .rst(rst),
                   .v1_1(v1_1),  // uint8
                   .v1_2(v1_2),  // uint8
                   .v2_1(v2_1),  // uint8
                   .v2_2(v2_2),  // uint8
                   .v3_1(v3_1),  // uint8
                   .v3_2(v3_2),  // uint8
                   .num_vx_x(num_vx_x),  // uint8
                   .SDI_1(in2bin_out1),
                   .SCK(in2bin_out2),
                   .nCS1(in2bin_out3),
                   .nCS2(in2bin_out4),
                   .nCS3(in2bin_out5)
                   );
  assign SDI = in2bin_out1;

  assign SCK = in2bin_out2;

  assign nCS1 = in2bin_out3;

  assign nCS2 = in2bin_out4;

  assign nCS3 = in2bin_out5;

endmodule  // model_int2bin_sdi

