// -------------------------------------------------------------
// 
// File Name: .\hdlsrc\int2bin_sdi\sdi.v
// Created: 2024-11-01 08:51:56
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: sdi
// Source Path: int2bin_sdi/model_int2bin_sdi/in2bin/sdi
// Hierarchy Level: 2
// Model version: 3.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module sdi
          (clk,
           rst,
           en_sdi,
           selector,
           vector_bin_0,
           vector_bin_1,
           vector_bin_2,
           vector_bin_3,
           vector_bin_4,
           vector_bin_5,
           vector_bin_6,
           vector_bin_7,
           done,
           SDI_1,
           SCK,
           nCS1,
           nCS2,
           nCS3);


  input   clk;
  input   rst;
  input   en_sdi;
  input   [7:0] selector;  // uint8
  input   vector_bin_0;  // boolean
  input   vector_bin_1;  // boolean
  input   vector_bin_2;  // boolean
  input   vector_bin_3;  // boolean
  input   vector_bin_4;  // boolean
  input   vector_bin_5;  // boolean
  input   vector_bin_6;  // boolean
  input   vector_bin_7;  // boolean
  output  done;
  output  SDI_1;
  output  SCK;
  output  nCS1;
  output  nCS2;
  output  nCS3;




  dispatcher u_dispatcher (.clk(clk),
                           .rst(rst),
                           .selector(selector),  // uint8
                           .vector_bin_0(vector_bin_0),  // boolean
                           .vector_bin_1(vector_bin_1),  // boolean
                           .vector_bin_2(vector_bin_2),  // boolean
                           .vector_bin_3(vector_bin_3),  // boolean
                           .vector_bin_4(vector_bin_4),  // boolean
                           .vector_bin_5(vector_bin_5),  // boolean
                           .vector_bin_6(vector_bin_6),  // boolean
                           .vector_bin_7(vector_bin_7),  // boolean
                           .en_sdi(en_sdi),
                           .done(done),
                           .SDI(SDI_1),
                           .SCK(SCK),
                           .nCS1(nCS1),
                           .nCS2(nCS2),
                           .nCS3(nCS3)
                           );
endmodule  // sdi

