// -------------------------------------------------------------
// 
// File Name: C:\Users\angro\Desktop\hil\dac\SPI_DAC\int2bin_sdi\SPI_DAC.v
// Created: 2024-11-01 19:07:18
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 20
// Target subsystem base rate: 20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SPI_DAC
// Source Path: int2bin_sdi/SPI_DAC
// Hierarchy Level: 0
// Model version: 3.41
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SPI_DAC
          (clk,
           rst,
           numer_vx,
           v1_1,
           v1_2,
           v2_1,
           v2_2,
           v3_1,
           v3_2,
           SDI,
           SCK,
           nCS1,
           nCS2,
           nCS3);


  input   clk;
  input   rst;
  input   [7:0] numer_vx;  // uint8
  input   [7:0] v1_1;  // uint8
  input   [7:0] v1_2;  // uint8
  input   [7:0] v2_1;  // uint8
  input   [7:0] v2_2;  // uint8
  input   [7:0] v3_1;  // uint8
  input   [7:0] v3_2;  // uint8
  output  SDI;
  output  SCK;
  output  nCS1;
  output  nCS2;
  output  nCS3;




  SPI_MNGR u_SPI_MNGR (.clk(clk),
                       .rst(rst),
                       .numer_vx(numer_vx),  // uint8
                       .v3_2(v3_2),  // uint8
                       .v3_1(v3_1),  // uint8
                       .v1_2(v1_2),  // uint8
                       .v2_1(v2_1),  // uint8
                       .v2_2(v2_2),  // uint8
                       .v1_1(v1_1),  // uint8
                       .SDI(SDI),
                       .SCK(SCK),
                       .nCS1(nCS1),
                       .nCS2(nCS2),
                       .nCS3(nCS3)
                       );
endmodule  // SPI_DAC

