// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\compar\compar_tc.v
// Created: 2025-05-02 14:13:07
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: compar_tc
// Source Path: compar_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb_20000000_1_0: identical to clk_enable
// enb_1_1_1   : 20000000x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module compar_tc
          (clk,
           reset,
           clk_enable,
           enb_20000000_1_0,
           enb_1_1_1);


  input   clk;
  input   reset;
  input   clk_enable;
  output  enb_20000000_1_0;
  output  enb_1_1_1;


  reg [24:0] count20000000;  // ufix25
  wire comp_1_tmp;
  wire phase_1_tmp;
  reg  phase_1;
  wire enb_1_1_1_1;


  assign enb_20000000_1_0 = clk_enable;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 19999999
  always @(posedge clk or posedge reset)
    begin : counter_20000000_process
      if (reset == 1'b1) begin
        count20000000 <= 25'b0000000000000000000000001;
      end
      else begin
        if (clk_enable) begin
          if (count20000000 >= 25'b1001100010010110011111111) begin
            count20000000 <= 25'b0000000000000000000000000;
          end
          else begin
            count20000000 <= count20000000 + 25'b0000000000000000000000001;
          end
        end
      end
    end

  assign comp_1_tmp = count20000000 == 25'b0000000000000000000000000;

  assign phase_1_tmp = comp_1_tmp & clk_enable;

  always @(posedge clk or posedge reset)
    begin : phase_delay_process
      if (reset == 1'b1) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clk_enable) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end

  assign enb_1_1_1_1 = phase_1 & clk_enable;

  assign enb_1_1_1 = enb_1_1_1_1;

endmodule  // compar_tc

