// -------------------------------------------------------------
// 
// File Name: .\hdlsrc\amc_simulator\vac_gen.v
// Created: 2024-10-29 18:54:36
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: vac_gen
// Source Path: amc_simulator/amc_simulator/vac_gen
// Hierarchy Level: 1
// Model version: 3.8
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module vac_gen
          (v,
           dc_vb);


  input   [7:0] v;  // uint8
  output  [7:0] dc_vb;  // uint8


  wire [7:0] const_50_out1;  // uint8
  wire [7:0] vb;  // uint8


  assign const_50_out1 = 8'b00011100;
  assign vb = v;

  assign dc_vb = const_50_out1 + vb;
endmodule  // vac_gen

