// -------------------------------------------------------------
// 
// File Name: .\hdlsrc\int2bin_sdi\model_int2bin_sdi.v
// Created: 2024-09-18 12:34:23
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 8.33333e-09
// Target subsystem base rate: 1.66667e-07
// Explicit user oversample request: 2x
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1.66667e-07
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// SDI                           ce_out        1.66667e-07
// SCK                           ce_out        1.66667e-07
// nCS1                          ce_out        1.66667e-07
// nCS2                          ce_out        1.66667e-07
// nCS3                          ce_out        1.66667e-07
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: model_int2bin_sdi
// Source Path: int2bin_sdi/model_int2bin_sdi
// Hierarchy Level: 0
// Model version: 1.47
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module model_int2bin_sdi# (
	parameter num_vx_x = 6
	)
          (clk,
           rst,
           clk_enable,
           v1_1,
           v1_2,
           v2_1,
           v2_2,
           v3_1,
           v3_2,
           SDI,
           SCK,
           nCS1,
           nCS2,
           nCS3);


  input   clk;
  input   rst;
  input   clk_enable;
  input   [7:0] v1_1;  // uint8
  input   [7:0] v1_2;  // uint8
  input   [7:0] v2_1;  // uint8
  input   [7:0] v2_2;  // uint8
  input   [7:0] v3_1;  // uint8
  input   [7:0] v3_2;  // uint8
  
  //output  ce_out;
  output  SDI;
  output  SCK;
  output  nCS1;
  output  nCS2;
  output  nCS3;

  wire [7:0] Constant_out1x;
  wire enb_1_20_0;
  wire enb_1_20_1;
  wire enb_1_10_0;
  wire in2bin_out1;
  wire in2bin_out2;
  wire in2bin_out3;
  wire in2bin_out4;
  wire in2bin_out5;
    
  assign Constant_out1x =   num_vx_x;

  model_int2bin_sdi_tc u_model_int2bin_sdi_tc (.clk(clk),
                                               .rst(rst),
                                               .clk_enable(clk_enable),
                                               .enb_1_10_0(enb_1_10_0),
                                               .enb_1_20_0(enb_1_20_0),
                                               .enb_1_20_1(enb_1_20_1)
                                               );

  in2bin u_in2bin (.clk(clk),
                   .rst(rst),
                   .enb_1_20_0(enb_1_20_0),
                   .v1_1(v1_1),  // uint8
                   .v1_2(v1_2),  // uint8
                   .v2_1(v2_1),  // uint8
                   .v2_2(v2_2),  // uint8
                   .v3_1(v3_1),  // uint8
                   .v3_2(v3_2),  // uint8
                   .num_vx_x(num_vx_x),  // uint8
                   .SDI_1(in2bin_out1),
                   .SCK(in2bin_out2),
                   .nCS1(in2bin_out3),
                   .nCS2(in2bin_out4),
                   .nCS3(in2bin_out5)
                   );
  assign SDI = in2bin_out1;

  assign SCK = in2bin_out2;

  assign nCS1 = in2bin_out3;

  assign nCS2 = in2bin_out4;

  assign nCS3 = in2bin_out5;

  //assign ce_out = enb_1_20_1;

endmodule  // model_int2bin_sdi

