// -------------------------------------------------------------
// 
// File Name: sine_gen\sine_gen\alpha200kHz.v
// Created: 2024-10-31 19:07:34
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: alpha200kHz
// Source Path: sine_gen/Subsystem/200kHz
// Hierarchy Level: 1
// Model version: 1.7
// 
// Sine Wave
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module alpha200kHz
          (clk,
           Sine_Wave_out1);


  input   clk;
  output  signed [15:0] Sine_Wave_out1;  // int16


  reg [4:0] address_cnt1;  // ufix5
  wire signed [15:0] lut1out1;  // int16

  initial begin
    address_cnt1 = 5'b00000;
  end

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 24
  always @(posedge clk)
    begin : Sine_Wave_addrcnt_temp_process1_process
      if (address_cnt1 >= 5'b11000) begin
        address_cnt1 <= 5'b00000;
      end
      else begin
        address_cnt1 <= address_cnt1 + 5'b00001;
      end
    end

  Lookup_Table3_block u_Lookup_Table3 (.in1(address_cnt1),  // ufix5
                                       .out(lut1out1)  // int16
                                       );

  assign Sine_Wave_out1 = lut1out1;

endmodule  // alpha200kHz

