// -------------------------------------------------------------
// 
// File Name: sine_gen\sine_gen\alpha100kHz.v
// Created: 2024-10-31 19:07:34
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: alpha100kHz
// Source Path: sine_gen/Subsystem/100kHz
// Hierarchy Level: 1
// Model version: 1.7
// 
// Sine Wave
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module alpha100kHz
          (clk,
           Sine_Wave_out1);


  input   clk;
  output  signed [15:0] Sine_Wave_out1;  // int16


  reg [5:0] address_cnt1;  // ufix6
  wire signed [15:0] lut1out1;  // int16

  initial begin
    address_cnt1 = 6'b000000;
  end

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 49
  always @(posedge clk)
    begin : Sine_Wave_addrcnt_temp_process1_process
      if (address_cnt1 >= 6'b110001) begin
        address_cnt1 <= 6'b000000;
      end
      else begin
        address_cnt1 <= address_cnt1 + 6'b000001;
      end
    end

  Lookup_Table3 u_Lookup_Table3 (.in1(address_cnt1),  // ufix6
                                 .out(lut1out1)  // int16
                                 );

  assign Sine_Wave_out1 = lut1out1;

endmodule  // alpha100kHz

