// -------------------------------------------------------------
// 
// File Name: sine_gen\sine_gen\Lookup_Table3.v
// Created: 2024-10-31 19:07:34
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Lookup_Table3
// Source Path: sine_gen/Subsystem/100kHz/Lookup Table3
// Hierarchy Level: 2
// Model version: 1.7
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Lookup_Table3
          (in1,
           out);


  input   [5:0] in1;  // ufix6
  output  signed [15:0] out;  // int16


  wire [5:0] prelookup_idx_sat;  // ufix6
  wire [5:0] prelookup_idx;  // ufix6
  wire signed [15:0] Lookup_Table3_table_data [0:49];  // sfix16 [50]


  assign prelookup_idx_sat = (in1 == 6'b000000 ? 6'b000000 :
              (in1 >= 6'b110001 ? 6'b110001 :
              in1));

  assign prelookup_idx = (prelookup_idx_sat > 6'b110001 ? 6'b110001 :
              prelookup_idx_sat);

  assign Lookup_Table3_table_data[0] = 16'sb0000000000000000;
  assign Lookup_Table3_table_data[1] = 16'sb0000000000001100;
  assign Lookup_Table3_table_data[2] = 16'sb0000000000011000;
  assign Lookup_Table3_table_data[3] = 16'sb0000000000100100;
  assign Lookup_Table3_table_data[4] = 16'sb0000000000110000;
  assign Lookup_Table3_table_data[5] = 16'sb0000000000111010;
  assign Lookup_Table3_table_data[6] = 16'sb0000000001000100;
  assign Lookup_Table3_table_data[7] = 16'sb0000000001001101;
  assign Lookup_Table3_table_data[8] = 16'sb0000000001010100;
  assign Lookup_Table3_table_data[9] = 16'sb0000000001011010;
  assign Lookup_Table3_table_data[10] = 16'sb0000000001011111;
  assign Lookup_Table3_table_data[11] = 16'sb0000000001100010;
  assign Lookup_Table3_table_data[12] = 16'sb0000000001100011;
  assign Lookup_Table3_table_data[13] = 16'sb0000000001100011;
  assign Lookup_Table3_table_data[14] = 16'sb0000000001100010;
  assign Lookup_Table3_table_data[15] = 16'sb0000000001011111;
  assign Lookup_Table3_table_data[16] = 16'sb0000000001011010;
  assign Lookup_Table3_table_data[17] = 16'sb0000000001010100;
  assign Lookup_Table3_table_data[18] = 16'sb0000000001001101;
  assign Lookup_Table3_table_data[19] = 16'sb0000000001000100;
  assign Lookup_Table3_table_data[20] = 16'sb0000000000111010;
  assign Lookup_Table3_table_data[21] = 16'sb0000000000110000;
  assign Lookup_Table3_table_data[22] = 16'sb0000000000100100;
  assign Lookup_Table3_table_data[23] = 16'sb0000000000011000;
  assign Lookup_Table3_table_data[24] = 16'sb0000000000001100;
  assign Lookup_Table3_table_data[25] = 16'sb0000000000000000;
  assign Lookup_Table3_table_data[26] = 16'sb1111111111110100;
  assign Lookup_Table3_table_data[27] = 16'sb1111111111101000;
  assign Lookup_Table3_table_data[28] = 16'sb1111111111011100;
  assign Lookup_Table3_table_data[29] = 16'sb1111111111010000;
  assign Lookup_Table3_table_data[30] = 16'sb1111111111000110;
  assign Lookup_Table3_table_data[31] = 16'sb1111111110111100;
  assign Lookup_Table3_table_data[32] = 16'sb1111111110110011;
  assign Lookup_Table3_table_data[33] = 16'sb1111111110101100;
  assign Lookup_Table3_table_data[34] = 16'sb1111111110100110;
  assign Lookup_Table3_table_data[35] = 16'sb1111111110100001;
  assign Lookup_Table3_table_data[36] = 16'sb1111111110011110;
  assign Lookup_Table3_table_data[37] = 16'sb1111111110011101;
  assign Lookup_Table3_table_data[38] = 16'sb1111111110011101;
  assign Lookup_Table3_table_data[39] = 16'sb1111111110011110;
  assign Lookup_Table3_table_data[40] = 16'sb1111111110100001;
  assign Lookup_Table3_table_data[41] = 16'sb1111111110100110;
  assign Lookup_Table3_table_data[42] = 16'sb1111111110101100;
  assign Lookup_Table3_table_data[43] = 16'sb1111111110110011;
  assign Lookup_Table3_table_data[44] = 16'sb1111111110111100;
  assign Lookup_Table3_table_data[45] = 16'sb1111111111000110;
  assign Lookup_Table3_table_data[46] = 16'sb1111111111010000;
  assign Lookup_Table3_table_data[47] = 16'sb1111111111011100;
  assign Lookup_Table3_table_data[48] = 16'sb1111111111101000;
  assign Lookup_Table3_table_data[49] = 16'sb1111111111110100;
  assign out = Lookup_Table3_table_data[prelookup_idx];

endmodule  // Lookup_Table3

