// -------------------------------------------------------------
// 
// File Name: sine_gen\sine_gen\Subsystem_tc.v
// Created: 2024-10-30 18:35:32
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_tc
// Source Path: Subsystem_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb         : identical to clk_enable
// enb_1_10_0  : 10x slower than clk with last phase
// enb_1_10_1  : 10x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_tc
          (clk,
           clk_enable,
           enb,
           enb_1_10_0,
           enb_1_10_1);


  input   clk;
  input   clk_enable;
  output  enb;
  output  enb_1_10_0;
  output  enb_1_10_1;


  reg [3:0] count10;  // ufix4
  wire comp_0_tmp;
  wire phase_0_tmp;
  reg  phase_0;
  wire enb_1_10_0_1;
  wire phase_delay_ctrl_const_out;
  reg  phase_delay_ctrl_delay_out;
  wire phase_delay_Initial_Val_out;
  wire comp_1_tmp;
  wire phase_1_tmp;
  reg  phase_delay_out;
  wire phase_1;
  wire enb_1_10_1_1;

  initial begin
    count10 = 4'b0001;
    phase_0 = 1'b0;
    phase_delay_ctrl_delay_out = 1'b0;
    phase_delay_out = 1'b0;
  end

  assign enb = clk_enable;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 9
  always @(posedge clk)
    begin : counter_10_process
      if (clk_enable) begin
        if (count10 >= 4'b1001) begin
          count10 <= 4'b0000;
        end
        else begin
          count10 <= count10 + 4'b0001;
        end
      end
    end

  assign comp_0_tmp = count10 == 4'b1001;

  assign phase_0_tmp = comp_0_tmp & clk_enable;

  always @(posedge clk)
    begin : phase_delay_process
      if (clk_enable) begin
        phase_0 <= phase_0_tmp;
      end
    end

  assign enb_1_10_0_1 = phase_0 & clk_enable;

  assign enb_1_10_0 = enb_1_10_0_1;

  assign phase_delay_ctrl_const_out = 1'b1;

  always @(posedge clk)
    begin : phase_delay_ctrl_delay_process
      if (clk_enable) begin
        phase_delay_ctrl_delay_out <= phase_delay_ctrl_const_out;
      end
    end

  assign phase_delay_Initial_Val_out = 1'b1;

  assign comp_1_tmp = count10 == 4'b0000;

  assign phase_1_tmp = comp_1_tmp & clk_enable;

  always @(posedge clk)
    begin : phase_delay_1_process
      if (clk_enable) begin
        phase_delay_out <= phase_1_tmp;
      end
    end

  assign phase_1 = (phase_delay_ctrl_delay_out == 1'b0 ? phase_delay_Initial_Val_out :
              phase_delay_out);

  assign enb_1_10_1_1 = phase_1 & clk_enable;

  assign enb_1_10_1 = enb_1_10_1_1;

endmodule  // Subsystem_tc

