// -------------------------------------------------------------
// 
// File Name: sine_gen\sine_gen\Subsystem.v
// Created: 2024-10-31 19:07:34
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 2e-07
// Target subsystem base rate: 2e-07
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem
// Source Path: sine_gen/Subsystem
// Hierarchy Level: 0
// Model version: 1.7
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem
          (clk,
           out_50kHz,
           out_100kHz,
           out_200kHz);


  input   clk;
  output  [7:0] out_50kHz;  // uint8
  output  [7:0] out_100kHz;  // uint8
  output  [7:0] out_200kHz;  // uint8


  wire [7:0] Constant_out1;  // uint8
  wire signed [15:0] alpha50kHz_out1;  // int16
  wire [7:0] Data_Type_Conversion_out1;  // uint8
  wire [7:0] Add2_out1;  // uint8
  wire signed [15:0] alpha100kHz_out1;  // int16
  wire [7:0] Data_Type_Conversion1_out1;  // uint8
  wire [7:0] Add1_out1;  // uint8
  wire signed [15:0] alpha200kHz_out1;  // int16
  wire [7:0] Data_Type_Conversion2_out1;  // uint8
  wire [7:0] Add_out1;  // uint8


  assign Constant_out1 = 8'b01101110;

  alpha50kHz u_50kHz (.clk(clk),
                      .Sine_Wave_out1(alpha50kHz_out1)  // int16
                      );

  assign Data_Type_Conversion_out1 = alpha50kHz_out1[7:0];

  assign Add2_out1 = Constant_out1 + Data_Type_Conversion_out1;

  assign out_50kHz = Add2_out1;

  alpha100kHz u_100kHz (.clk(clk),
                        .Sine_Wave_out1(alpha100kHz_out1)  // int16
                        );

  assign Data_Type_Conversion1_out1 = alpha100kHz_out1[7:0];

  assign Add1_out1 = Constant_out1 + Data_Type_Conversion1_out1;

  assign out_100kHz = Add1_out1;

  alpha200kHz u_200kHz (.clk(clk),
                        .Sine_Wave_out1(alpha200kHz_out1)  // int16
                        );

  assign Data_Type_Conversion2_out1 = alpha200kHz_out1[7:0];

  assign Add_out1 = Constant_out1 + Data_Type_Conversion2_out1;

  assign out_200kHz = Add_out1;

endmodule  // Subsystem

